@startuml
title US-02-Consultar Usuarios

actor Administrador

boundary  "users.ejs" as M4
boundary  "userRoutes.js" as M1
control  "getUsersController.js" as M2
entity  "User.js" as M3
database "MongoDB" as DB

== Frontend ==
Administrador -> M4 : Clic en boton 'Usuarios' 


M4 -> M1 : GET /usuarios

== Backend ==
M1 ->> M2 : controller.getUsers(req,res)
M2 ->> M3 : User.getAllUsers()
M3 ->> DB : User.find()


DB -->> M3 : Array BSON de usuarios
M3 -->> M2 : Array de usuarios
M2 --> M4 : res.render('/usuarios', { users: users })

alt Error BD
    DB -->> M3 : Error de conexión (code)
    M3 -->> M2 : Retorna error { code, message}
    M2 --> M4 : res.render('includes/500') 
end



@enduml
