@startuml
title US-01-Consultar dashboard principal

actor Administrador

boundary "dashboard.ejs" as View
control "dashboard.js" as JS
boundary "dashboardRoutes.js" as R
control "dashboardController.js" as C
entity "reporteModel.js" as M_Reporte
entity "userModel.js" as M_User
entity "unitModel.js" as M_Unit
database "MongoDB" as DB

== Frontend ==
alt Filtro por día
    Administrador -> View: Interacción con el filtro

    activate View
    View -> JS: onFilterChange("day")
    deactivate View

    activate JS
    JS -> R: GET /dashboard?filter=day
    deactivate JS

    activate R
    R -> C: getConsultDashboard(req, res)
    deactivate R

    activate C

else Filtro por semana
    Administrador -> View: Interacción con el filtro

    activate View
    View -> JS: onFilterChange("week")
    deactivate View

    activate JS
    JS -> R: GET /dashboard?filter=week
    deactivate JS

    activate R
    R -> C: getConsultDashboard(req, res)
    deactivate R

else Filtro por mes
    Administrador -> View: Interacción con el filtro

    activate View
    View -> JS: onFilterChange("month")
    deactivate View

    activate JS
    JS -> R: GET /dashboard?filter=month
    deactivate JS

    activate R
    R -> C: getConsultDashboard(req, res)
    deactivate R

else sin interacción con el filtro
    Administrador -> R: GET /dashboard?filter=week

    activate R
    R -> C: getConsultDashboard(req, res)
    deactivate R
end


== Backend ==
C ->> M_Reporte: fetchAll(filterByDate)

activate M_Reporte
M_Reporte ->> DB: db.execute(query with filter)

activate DB
DB -->> M_Reporte: Datos de reportes
deactivate DB

M_Reporte -->> C: Datos de reportes
deactivate M_Reporte

loop Por cada reporte de datos
    C ->> M_User: fetchById(userId)
activate M_User
    M_User ->> DB: db.execute(query)

    activate DB
    DB -->> M_User: username
    deactivate DB

    M_User -->> C: username
    deactivate M_User

    C ->> M_Unit: fetchById(unitId)

    activate M_Unit
    M_Unit ->> DB: db.execute(query)

    activate DB
    DB -->> M_Unit: unitname
    deactivate DB

    M_Unit -->> C: unitname
    deactivate M_Unit
end

== Frontend ==
alt Promesa exitosa (status 200)
    C -> JS: JSON
    
    activate JS
    JS -> View: Actualizar datos
    deactivate JS
    
    activate View
    View -> Administrador: Vista actualizada
    deactivate View
else Promesa no exitosa (status 500)
    C -> JS: JSON
    deactivate C

    activate JS
    JS -> View: Mostrar mensaje de error
    deactivate JS

    activate View
    View -> Administrador: Error al cargar datos
    deactivate View
end


@enduml
