@startuml
title US-01-Consultar dashboard principal

actor Administrador

boundary "dashboardRoutes.js" as R
boundary "dashboard.ejs" as View
control "dashboardController.js" as C
entity "reporteModel.js" as M_Reporte
entity "userModel.js" as M_User
entity "unitModel.js" as M_Unit
database "MongoDB" as DB

== Frontend ==
Administrador -> R: GET /dashboard

activate R
R -> C: getConsultDashboard(req, res)
deactivate R

== Backend ==
activate C
C ->> M_Reporte: fetchAll()

activate M_Reporte
M_Reporte ->> DB: db.execute(query)

activate DB
DB -->> M_Reporte: Datos de reportes
deactivate DB

M_Reporte -->> C: Datos de reportes
deactivate M_Reporte

loop Por cada reporte de datos
    C ->> M_User: fetchById(userId)
activate M_User
    M_User ->> DB: db.execute(query)

    activate DB
    DB -->> M_User: username
    deactivate DB

    M_User -->> C: username
    deactivate M_User

    C ->> M_Unit: fetchById(unitId)

    activate M_Unit
    M_Unit ->> DB: db.execute(query)

    activate DB
    DB -->> M_Unit: unitname
    deactivate DB

    M_Unit -->> C: unitname
    deactivate M_Unit
end

== Frontend ==
C -> View: response.render(unitname, username, mileage, efficiency, photoLiters, loadDate)
deactivate C

activate View
View -> Administrador: HTML
deactivate View

@enduml
