@startuml
title US-11-Recuperar contraseña

actor Administrador as admin

boundary "userRoutes.js" as route
boundary "confirmEmail.ejs" as confirmEmail
boundary "resetPassword.ejs" as resetPassword
boundary "login.ejs" as login
boundary "nodemailer.js" as nodemailer
control "resetPasswordController.js" as controller
entity "userModel.js" as model
database "MongoDB" as DB

== Frontend ==
admin -> route ++: GET('/users/confirm-email')
route -> controller --++ : getConfirmEmail(request, response, next)
controller -> confirmEmail -- : render('confirmEmail.ejs')
admin -> route ++: POST('/users/confirm-email')

== Backend ==
route ->> controller --++: postConfirmEmail(request, response, next)
controller ->> model ++: findByEmail({ email })
model ->> DB : findOne({ email : email })
DB -->> model : user
model -->> controller -- : user

alt (user != null) && (user.role == "Admin")
    controller -> nodemailer : sendEmail(html, user.email, subject)
end
controller--

== Frontend ==
admin -> route ++: GET('/users/set-password')
route -> controller --++ : getResetPassword(request, response, next)
controller -> resetPassword -- : render('resetPassword.ejs')
admin -> route ++: POST('/users/set-password')

== Backend ==
route ->> controller --++: postResetPassword(request, response, next)
alt jwt.verify(token, config.jwtSecret)
    controller ->> model ++: setPassword();
    model ->> DB : updateOne({ email : email }, { $set: { password: password } })
    DB -->> model : msg
    model -->> controller -- : msg
    controller -> login : render('login')
else err
    controller -> route -- : redirect('users/login')
end

@enduml
